"use strict";
const express = require("express");
const wantedController = require("../controllers/wanted.controller");
const authMiddleware = require("../middlewares/auth.middleware");
const uploadMiddleware = require("../middlewares/upload.middleware");
const router = express.Router();
router.use(authMiddleware.authenticateToken);
router.post('/', uploadMiddleware.upload.fields([{ name: 'fotoPrincipal', maxCount: 1 }]), wantedController.createWanted);
router.get('/', wantedController.listWanted);
router.get('/:id', wantedController.getWanted);
module.exports = router;
