-- FIX PROVAS TABLE - FULL SCHEMA REPAIR
-- This script ensures the 'provas' table has all necessary columns and policies.

-- 1. Ensure 'provas' table exists with basic structure
CREATE TABLE IF NOT EXISTS public.provas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Add missing columns safely
DO $$
BEGIN
    -- investigacao_id
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'provas' AND column_name = 'investigacao_id') THEN
        ALTER TABLE public.provas ADD COLUMN investigacao_id BIGINT REFERENCES public.investigacoes(id) ON DELETE CASCADE;
    END IF;

    -- tipo
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'provas' AND column_name = 'tipo') THEN
        ALTER TABLE public.provas ADD COLUMN tipo TEXT;
    END IF;

    -- url
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'provas' AND column_name = 'url') THEN
        ALTER TABLE public.provas ADD COLUMN url TEXT;
    END IF;

    -- descricao
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'provas' AND column_name = 'descricao') THEN
        ALTER TABLE public.provas ADD COLUMN descricao TEXT;
    END IF;

    -- uploaded_by
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'provas' AND column_name = 'uploaded_by') THEN
        ALTER TABLE public.provas ADD COLUMN uploaded_by UUID REFERENCES auth.users(id);
    END IF;
    
    -- data_upload (if you want to keep it separate from created_at, otherwise use created_at)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'provas' AND column_name = 'data_upload') THEN
        ALTER TABLE public.provas ADD COLUMN data_upload TIMESTAMP WITH TIME ZONE DEFAULT now();
    END IF;
END $$;

-- 3. Enable RLS
ALTER TABLE public.provas ENABLE ROW LEVEL SECURITY;

-- 4. Re-create Policies to be sure
DROP POLICY IF EXISTS "Authenticated users can view proofs" ON public.provas;
CREATE POLICY "Authenticated users can view proofs" ON public.provas
FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can insert proofs" ON public.provas;
CREATE POLICY "Authenticated users can insert proofs" ON public.provas
FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can update proofs" ON public.provas;
CREATE POLICY "Authenticated users can update proofs" ON public.provas
FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can delete proofs" ON public.provas;
CREATE POLICY "Authenticated users can delete proofs" ON public.provas
FOR DELETE USING (auth.role() = 'authenticated');

-- 5. Notify PostgREST to reload schema cache
NOTIFY pgrst, 'reload config';
