-- Tabela de Perfis de Usuários (vinculada ao Auth do Supabase)
create table public.profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  role text default 'Agente DICOR', -- Agente DICOR, Escrivão DICOR, Coordenador DICOR, Diretor DICOR
  avatar_url text,
  updated_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

-- Trigger para criar perfil automaticamente ao cadastrar usuário
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'name', 'Agente CERCO');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Tabela de Prisões
create table public.prisoes (
  id bigint generated by default as identity primary key,
  nome text not null,
  documento text,
  artigo text,
  data_prisao timestamp with time zone default now(),
  status text default 'Preso', -- Preso, Liberado, Transferido
  foto_principal text,
  conduzido_por text,
  observacoes text,
  created_by uuid references auth.users,
  created_at timestamp with time zone default now()
);

-- Tabela de Procurados
create table public.procurados (
  id bigint generated by default as identity primary key,
  nome text not null,
  alcunha text,
  crime text,
  recompensa decimal,
  status text default 'Foragido', -- Foragido, Capturado, Morto
  foto text,
  mandado text,
  created_by uuid references auth.users,
  created_at timestamp with time zone default now()
);

-- Tabela de Investigações
create table public.investigacoes (
  id bigint generated by default as identity primary key,
  titulo text not null,
  status text default 'Em Aberto', -- Em Aberto, Em Andamento, Concluída, Arquivada
  prioridade text default 'Média', -- Baixa, Média, Alta
  data_inicio timestamp with time zone default now(),
  responsavel text,
  descricao text,
  created_by uuid references auth.users,
  created_at timestamp with time zone default now()
);

-- Tabela de Provas (Vinculada a Investigações)
create table public.provas (
  id bigint generated by default as identity primary key,
  investigacao_id bigint references public.investigacoes on delete cascade,
  tipo text, -- Foto, Documento, Audio, Video
  url text not null,
  descricao text,
  data_upload timestamp with time zone default now(),
  uploaded_by uuid references auth.users
);

-- Tabela de Logs do Sistema
create table public.system_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id), -- Relacionamento com profiles para pegar nome/cargo
  action text not null,
  details text,
  created_at timestamp with time zone default now()
);

-- Tabela de Candidatos (Formulário Faça Parte)
create table public.candidatos (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text,
  telefone text,
  mensagem text,
  status text default 'Pendente', -- Pendente, Em Análise, Aprovado, Rejeitado
  created_at timestamp with time zone default now()
);

-- Tabela de Cursos
create table public.cursos (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text,
  criado_por uuid references auth.users,
  created_at timestamp with time zone default now()
);

-- Tabela de Cursos dos Policiais (Relacionamento N:N)
create table public.cursos_policiais (
  id bigint generated by default as identity primary key,
  curso_id bigint references public.cursos on delete cascade,
  policial_id uuid references public.profiles(id) on delete cascade,
  data_atribuicao timestamp with time zone default now(),
  atribuido_por uuid references auth.users
);

-- Habilitar Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.prisoes enable row level security;
alter table public.procurados enable row level security;
alter table public.investigacoes enable row level security;
alter table public.provas enable row level security;
alter table public.system_logs enable row level security;
alter table public.candidatos enable row level security;
alter table public.cursos enable row level security;
alter table public.cursos_policiais enable row level security;

-- Policies (Políticas de Segurança)

-- Profiles: Leitura pública (para logs), Edição apenas pelo próprio usuário
create policy "Perfis são visíveis por todos os autenticados" on public.profiles
  for select using (auth.role() = 'authenticated');

create policy "Usuários podem editar seu próprio perfil" on public.profiles
  for update using (auth.uid() = id);

-- Prisões: Todos autenticados podem ver e criar
create policy "Prisões visíveis para logados" on public.prisoes
  for select using (auth.role() = 'authenticated');
  
create policy "Prisões visíveis publicamente (apenas contagem)" on public.prisoes
  for select using (true); -- Permitir leitura pública para estatísticas na Home

create policy "Agentes podem registrar prisões" on public.prisoes
  for insert with check (auth.role() = 'authenticated');

create policy "Apenas criador ou admin pode editar prisões" on public.prisoes
  for update using (auth.uid() = created_by); -- Pode expandir para checar role

-- Procurados: Todos ver e criar
create policy "Procurados visíveis para logados" on public.procurados
  for select using (auth.role() = 'authenticated');
  
create policy "Procurados visíveis publicamente (apenas contagem)" on public.procurados
  for select using (true); -- Permitir leitura pública para estatísticas na Home

create policy "Agentes podem registrar procurados" on public.procurados
  for insert with check (auth.role() = 'authenticated');

-- Investigações e Provas
create policy "Investigações visíveis para logados" on public.investigacoes
  for select using (auth.role() = 'authenticated');

create policy "Investigações visíveis publicamente (apenas contagem)" on public.investigacoes
  for select using (true); -- Permitir leitura pública para estatísticas na Home

create policy "Criar investigações" on public.investigacoes
  for insert with check (auth.role() = 'authenticated');

create policy "Provas visíveis para logados" on public.provas
  for select using (auth.role() = 'authenticated');

create policy "Adicionar provas" on public.provas
  for insert with check (auth.role() = 'authenticated');

-- Logs
create policy "Logs visíveis para logados" on public.system_logs
  for select using (auth.role() = 'authenticated');

create policy "Sistema pode criar logs" on public.system_logs
  for insert with check (auth.role() = 'authenticated');

-- Candidatos (Público pode inserir, Autenticados podem ver)
create policy "Qualquer um pode se candidatar" on public.candidatos
  for insert with check (true);

create policy "Apenas logados veem candidatos" on public.candidatos
  for select using (auth.role() = 'authenticated');

-- Cursos (Visível a todos, Apenas chefia cria/edita)
create policy "Cursos visíveis para todos" on public.cursos
  for select using (auth.role() = 'authenticated');

create policy "Apenas Diretor e Coordenador podem criar cursos" on public.cursos
  for insert with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role in ('Diretor CERCO', 'Coordenador CERCO')
    )
  );

create policy "Apenas Diretor e Coordenador podem editar cursos" on public.cursos
  for update using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role in ('Diretor CERCO', 'Coordenador CERCO')
    )
  );
  
create policy "Apenas Diretor e Coordenador podem deletar cursos" on public.cursos
  for delete using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role in ('Diretor CERCO', 'Coordenador CERCO')
    )
  );

-- Cursos Policiais (Visível a todos, Apenas chefia atribui)
create policy "Atribuições visíveis para todos" on public.cursos_policiais
  for select using (auth.role() = 'authenticated');

create policy "Apenas Diretor e Coordenador podem atribuir cursos" on public.cursos_policiais
  for insert with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role in ('Diretor CERCO', 'Coordenador CERCO')
    )
  );

create policy "Apenas Diretor e Coordenador podem remover atribuições" on public.cursos_policiais
  for delete using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role in ('Diretor CERCO', 'Coordenador CERCO')
    )
  );

-- Storage Buckets (Execute no painel do Supabase > Storage)
-- Criar buckets: 'prisoes', 'procurados', 'provas'
-- Configurar policies de Storage para 'authenticated' (INSERT/SELECT)
