-- Atualizar default role da tabela profiles (se já existir)
DO $$
BEGIN
    ALTER TABLE public.profiles ALTER COLUMN role SET DEFAULT 'Agente CERCO';
EXCEPTION
    WHEN undefined_table THEN
        RAISE NOTICE 'Tabela profiles ainda não existe.';
END $$;

-- Atualizar trigger handle_new_user
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'name', 'Agente CERCO');
  return new;
end;
$$ language plpgsql security definer;

-- Tabela de Cursos (Criar apenas se não existir)
create table if not exists public.cursos (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text,
  criado_por uuid references auth.users,
  created_at timestamp with time zone default now()
);

-- Tabela de Cursos dos Policiais (Criar apenas se não existir)
create table if not exists public.cursos_policiais (
  id bigint generated by default as identity primary key,
  curso_id bigint references public.cursos on delete cascade,
  policial_id uuid references public.profiles(id) on delete cascade,
  data_atribuicao timestamp with time zone default now(),
  atribuido_por uuid references auth.users
);

-- Habilitar RLS nas novas tabelas
alter table public.cursos enable row level security;
alter table public.cursos_policiais enable row level security;

-- Policies para Cursos
-- Remover policies antigas se existirem para evitar duplicidade
drop policy if exists "Cursos visíveis para todos" on public.cursos;
drop policy if exists "Apenas Diretor e Coordenador podem criar cursos" on public.cursos;
drop policy if exists "Apenas Diretor e Coordenador podem editar cursos" on public.cursos;
drop policy if exists "Apenas Diretor e Coordenador podem deletar cursos" on public.cursos;

create policy "Cursos visíveis para todos" on public.cursos
  for select using (auth.role() = 'authenticated');

create policy "Apenas Diretor e Coordenador podem criar cursos" on public.cursos
  for insert with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role in ('Diretor CERCO', 'Coordenador CERCO')
    )
  );

create policy "Apenas Diretor e Coordenador podem editar cursos" on public.cursos
  for update using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role in ('Diretor CERCO', 'Coordenador CERCO')
    )
  );
  
create policy "Apenas Diretor e Coordenador podem deletar cursos" on public.cursos
  for delete using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role in ('Diretor CERCO', 'Coordenador CERCO')
    )
  );

-- Policies para Cursos Policiais
drop policy if exists "Atribuições visíveis para todos" on public.cursos_policiais;
drop policy if exists "Apenas Diretor e Coordenador podem atribuir cursos" on public.cursos_policiais;
drop policy if exists "Apenas Diretor e Coordenador podem remover atribuições" on public.cursos_policiais;

create policy "Atribuições visíveis para todos" on public.cursos_policiais
  for select using (auth.role() = 'authenticated');

create policy "Apenas Diretor e Coordenador podem atribuir cursos" on public.cursos_policiais
  for insert with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role in ('Diretor CERCO', 'Coordenador CERCO')
    )
  );

create policy "Apenas Diretor e Coordenador podem remover atribuições" on public.cursos_policiais
  for delete using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role in ('Diretor CERCO', 'Coordenador CERCO')
    )
  );
