import { useCallback } from 'react';
import { useAuth } from '../context/AuthContext';

const PERMISSIONS = {
  BO_VIEW: 'bo_view', BO_MANAGE: 'bo_manage',
  ARREST_VIEW: 'arrest_view', ARREST_MANAGE: 'arrest_manage',
  WANTED_VIEW: 'wanted_view', WANTED_MANAGE: 'wanted_manage',
  REPORTS_VIEW: 'reports_view', REPORTS_MANAGE: 'reports_manage',
  JUDICIARY_VIEW: 'judiciary_view', JUDICIARY_MANAGE: 'judiciary_manage',
  REVENUE_VIEW: 'revenue_view', REVENUE_MANAGE: 'revenue_manage',
  INVESTIGATIONS_VIEW: 'investigations_view', INVESTIGATIONS_MANAGE: 'investigations_manage',
  FORENSICS_VIEW: 'forensics_view', FORENSICS_MANAGE: 'forensics_manage',
  ADMIN_ACCESS: 'admin_access',
  WEAPONS_VIEW: 'weapons_view', WEAPONS_MANAGE: 'weapons_manage',
  PROTECTIVE_MEASURES_VIEW: 'protective_measures_view', PROTECTIVE_MEASURES_MANAGE: 'protective_measures_manage',
  EXONERATIONS_VIEW: 'exonerations_view', EXONERATIONS_MANAGE: 'exonerations_manage',
  INTEGRATION_VIEW: 'integration_view', INTEGRATION_MANAGE: 'integration_manage',
  LOGISTICS_VIEW: 'logistics_view', LOGISTICS_MANAGE: 'logistics_manage',
  COMMUNICATION_VIEW: 'communication_view', COMMUNICATION_MANAGE: 'communication_manage',
  PM_VIEW: 'pm_view', PM_MANAGE: 'pm_manage',
  LAUDOS_VIEW: 'laudos_view', LAUDOS_MANAGE: 'laudos_manage',
  LAWYER_VIEW: 'lawyer_view', LAWYER_MANAGE: 'lawyer_manage',
  COURSES_VIEW: 'courses_view', COURSES_MANAGE: 'courses_manage',
  ANP_VIEW: 'anp_view', ANP_MANAGE: 'anp_manage',
  SETTINGS_VIEW: 'settings_view', SETTINGS_MANAGE: 'settings_manage',
  WARNINGS_VIEW: 'warnings_view', WARNINGS_MANAGE: 'warnings_manage',
  NEWS_VIEW: 'news_view', NEWS_MANAGE: 'news_manage',
  LOGS_VIEW: 'logs_view',
  CORPORATION_VIEW: 'corporation_view', APPEARANCE_VIEW: 'appearance_view',
  SECURITY_VIEW: 'security_view', BACKUP_VIEW: 'backup_view',
  HEALTH_VIEW: 'health_view', TEMPLATES_VIEW: 'templates_view',
  FORMS_VIEW: 'forms_view', EXAMS_VIEW: 'exams_view',
};

const ALL = Object.values(PERMISSIONS);

const ROLE_PERMISSIONS = {
  'Comandante Geral': ALL, 'Diretor': ALL, 'Coronel': ALL,
  'Major': ALL, 'Capitão': ALL, 'Tenente': ALL,

  'Aluno': [PERMISSIONS.COMMUNICATION_VIEW, PERMISSIONS.LOGISTICS_VIEW],

  'Sargento': [
    PERMISSIONS.BO_VIEW, PERMISSIONS.BO_MANAGE,
    PERMISSIONS.ARREST_VIEW, PERMISSIONS.ARREST_MANAGE,
    PERMISSIONS.WANTED_VIEW, PERMISSIONS.WANTED_MANAGE,
    PERMISSIONS.PROTECTIVE_MEASURES_VIEW, PERMISSIONS.PROTECTIVE_MEASURES_MANAGE,
    PERMISSIONS.EXONERATIONS_VIEW, PERMISSIONS.EXONERATIONS_MANAGE,
    PERMISSIONS.INTEGRATION_VIEW, PERMISSIONS.INTEGRATION_MANAGE,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_MANAGE,
    PERMISSIONS.INVESTIGATIONS_VIEW, PERMISSIONS.INVESTIGATIONS_MANAGE,
    PERMISSIONS.FORENSICS_VIEW, PERMISSIONS.REVENUE_VIEW,
    PERMISSIONS.NEWS_VIEW, PERMISSIONS.NEWS_MANAGE,
    PERMISSIONS.LOGS_VIEW, PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.COURSES_VIEW, PERMISSIONS.CORPORATION_VIEW, PERMISSIONS.APPEARANCE_VIEW,
  ],

  'Cabo': [
    PERMISSIONS.BO_VIEW, PERMISSIONS.BO_MANAGE,
    PERMISSIONS.ARREST_VIEW, PERMISSIONS.ARREST_MANAGE,
    PERMISSIONS.WANTED_VIEW,
    PERMISSIONS.PROTECTIVE_MEASURES_VIEW, PERMISSIONS.PROTECTIVE_MEASURES_MANAGE,
    PERMISSIONS.EXONERATIONS_VIEW, PERMISSIONS.EXONERATIONS_MANAGE,
    PERMISSIONS.INTEGRATION_VIEW, PERMISSIONS.INTEGRATION_MANAGE,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.INVESTIGATIONS_VIEW,
    PERMISSIONS.NEWS_VIEW, PERMISSIONS.NEWS_MANAGE,
    PERMISSIONS.LOGS_VIEW, PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.COURSES_VIEW,
  ],

  'Agente': [
    PERMISSIONS.BO_VIEW, PERMISSIONS.BO_MANAGE,
    PERMISSIONS.ARREST_VIEW, PERMISSIONS.ARREST_MANAGE,
    PERMISSIONS.WANTED_VIEW,
    PERMISSIONS.PROTECTIVE_MEASURES_VIEW, PERMISSIONS.PROTECTIVE_MEASURES_MANAGE,
    PERMISSIONS.EXONERATIONS_VIEW, PERMISSIONS.EXONERATIONS_MANAGE,
    PERMISSIONS.INTEGRATION_VIEW, PERMISSIONS.INTEGRATION_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.NEWS_VIEW, PERMISSIONS.NEWS_MANAGE,
    PERMISSIONS.LOGS_VIEW, PERMISSIONS.SETTINGS_VIEW,
  ],

  'Recruta': [
    PERMISSIONS.BO_VIEW, PERMISSIONS.ARREST_VIEW,
    PERMISSIONS.PROTECTIVE_MEASURES_VIEW, PERMISSIONS.EXONERATIONS_VIEW,
    PERMISSIONS.INTEGRATION_VIEW,
  ],

  'Juiz': [
    PERMISSIONS.JUDICIARY_VIEW, PERMISSIONS.JUDICIARY_MANAGE,
    PERMISSIONS.BO_VIEW, PERMISSIONS.ARREST_VIEW,
    PERMISSIONS.WANTED_VIEW, PERMISSIONS.INVESTIGATIONS_VIEW,
  ],

  'Advogado': [PERMISSIONS.JUDICIARY_VIEW, PERMISSIONS.ARREST_VIEW],
};

export const usePermissions = () => {
  const { user } = useAuth();

  const can = useCallback((permission) => {
    if (!user?.role) return false;
    if (user.role === 'Comandante Geral' || user.role === 'Developer') return true;

    const perm = permission === 'report_manage' ? PERMISSIONS.REPORTS_MANAGE : permission;
    const rolePerms = ROLE_PERMISSIONS[user.role] || [];
    const dynamicPerms = user.permissions || [];

    return rolePerms.includes(perm) || dynamicPerms.includes(perm);
  }, [user?.role, user?.permissions]);

  const hasRole = useCallback((roleName) => user?.role === roleName, [user?.role]);

  return { can, hasRole, user };
};
