
-- Tabela de Etapas do Curso ANP
CREATE TABLE IF NOT EXISTS public.anp_stages (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  "order" int default 0
);

-- Tabela de Progresso do Aluno ANP
CREATE TABLE IF NOT EXISTS public.user_anp_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  stage_id bigint references public.anp_stages(id) on delete cascade,
  status text default 'pending', -- pending, completed
  completed_at timestamp with time zone,
  completed_by uuid references auth.users,
  unique(user_id, stage_id)
);

-- Habilitar RLS
ALTER TABLE public.anp_stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_anp_progress ENABLE ROW LEVEL SECURITY;

-- Policies para anp_stages (Todos podem ver)
DROP POLICY IF EXISTS "Todos podem ver etapas ANP" ON public.anp_stages;
CREATE POLICY "Todos podem ver etapas ANP" ON public.anp_stages
  FOR SELECT USING (auth.role() = 'authenticated');

-- Policies para user_anp_progress
DROP POLICY IF EXISTS "Ver próprio progresso ou admin" ON public.user_anp_progress;
CREATE POLICY "Ver próprio progresso ou admin" ON public.user_anp_progress
  FOR SELECT USING (
    auth.uid() = user_id OR 
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role IN ('Diretor DPF', 'Coordenador DPF', 'Instrutor', 'Admin')
    )
  );

DROP POLICY IF EXISTS "Instrutores e Admins gerenciam progresso" ON public.user_anp_progress;
CREATE POLICY "Instrutores e Admins gerenciam progresso" ON public.user_anp_progress
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role IN ('Diretor DPF', 'Coordenador DPF', 'Instrutor', 'Admin')
    )
  );

-- Inserir dados iniciais se estiver vazio
INSERT INTO public.anp_stages (title, description, "order")
SELECT 'Módulo 1: Introdução e Ética', 'Regulamento interno, hierarquia e disciplina.', 1
WHERE NOT EXISTS (SELECT 1 FROM public.anp_stages WHERE "order" = 1);

INSERT INTO public.anp_stages (title, description, "order")
SELECT 'Módulo 2: Procedimentos Operacionais', 'Abordagem, algemação e condução.', 2
WHERE NOT EXISTS (SELECT 1 FROM public.anp_stages WHERE "order" = 2);

INSERT INTO public.anp_stages (title, description, "order")
SELECT 'Módulo 3: Armamento e Tiro', 'Manuseio seguro e prática de tiro.', 3
WHERE NOT EXISTS (SELECT 1 FROM public.anp_stages WHERE "order" = 3);

INSERT INTO public.anp_stages (title, description, "order")
SELECT 'Módulo 4: Legislação Aplicada', 'Código Penal e Processual Penal básico.', 4
WHERE NOT EXISTS (SELECT 1 FROM public.anp_stages WHERE "order" = 4);

INSERT INTO public.anp_stages (title, description, "order")
SELECT 'Prova Final', 'Avaliação geral para formatura.', 5
WHERE NOT EXISTS (SELECT 1 FROM public.anp_stages WHERE "order" = 5);
